okta:
  oauth2:
    issuer: https://dev-81525397.okta.com/oauth2/default
    client-id: 0oa10j8ylpONE5G995d7
#    client-id: 0oa10igyyltWYu51Y5d7
#    client-secret: xEAK28wM95N1RFovuglT7FylbTyPwGazqABKeQzb
    audience: http://localhost:8080
    scopes: openid profile email offline_access
#  openid profile email
spring:
  thymeleaf:
    cache: false